stages:
    - build
    - deploy
build:
    stage: build
    tags: 
        - mytag
    script:
        - echo "Building deploy package"
        - npm install
        - npm build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_production:
    stage: deploy
    tags: 
        - mytag
    script:
        - echo "Deploying to server"
        - npm run start
        - echo "Deployed"
    only:
        - main
